# Copyright (C) 2022 

$(call inherit-product, device/xiaomi/miatoll/device.mk)
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)

# Bootanimation 
TARGET_BOOT_ANIMATION_RES := 1080
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
SUSHI_BOOTANIMATION := 1080

PRODUCT_NAME := lineage_miatoll
PRODUCT_DEVICE := miatoll
PRODUCT_BRAND := Xiaomi
PRODUCT_MODEL := SM6250
PRODUCT_MANUFACTURER := Xiaomi
PRODUCT_GMS_CLIENTID_BASE := android-xiaomi
CUSTOM_DEVICE := miatoll

# Build Flags 
BUILD_USERNAME := iTS_UDAY_404
BUILD_HOSTNAME := RiceOS
TARGET_SUPPORTS_CALL_RECORDING := true
DEVICE_MAINTAINER := iTS_UDAY_404
SHIP_ANX := false

# RiceDroid Flags
RICE_DEVICE := miatoll
RICE_CHIPSET := atoll
RICE_OFFICIAL := false
RICE_MAINTAINER := iTS_UDAY_404
WITH_GMS := false
TARGET_SUPPORTS_QUICK_TAP := true
TARGET_BUILD_GRAPHENEOS_CAMERA := false
TARGET_FACE_UNLOCK_SUPPORTED := true
TARGET_ENABLE_BLUR := false

# FP at Brunch
PRODUCT_BUILD_PROP_OVERRIDES += \
    DEVICE_MAINTAINERS="iTS_UDAY_404" \
    PRIVATE_BUILD_DESC="raven-user 13 TP1A.220905.004 8927612 release-keys"

BUILD_FINGERPRINT := google/raven/raven:13/TP1A.220905.004/8927612:user/release-key
